### ISSUE TITLE
Is it possible to read multiple versions of cells?

### ISSUE THREAD

**Issue by Nivroc** [tkrs/orcus#432]
Hey. Not an issue per se, but a question:
Is it possible to use the maxVersions property of a scan and then transform result correctly using auto-derivations?

My code looks something like:
```
case class Event(primitive fields)
case class Family(e: Event)
implicit val decoder: Decoder[Family] = derivedDecoder[Family]
implicit val decoderEv: FamilyDecoder[Event] = derivedFamilyDecoder[Event]
...
response <- table.scanAll[F](asyncTable, scan)
result <- response.map(to[Family, F]).sequence
...
```
In the table I do have multiple versions of the same cell and the result from my scan is correct. However unmarshalling returns only one(last) version of the cell and I cannot do something like
`case class Family(e: List[Event])` since there is no decoder for List.
Is there a way of dealing with this with library means?

**Comment by tkrs** [comment]
Sorry for the late reply. Support for decoding multiple versions in [v0.26.0](https://github.com/tkrs/orcus/releases/tag/v0.26.0)
